### PR TITLE
fix yandex long URI error

### LINKED ISSUE #163: URI Too Long for Yandex
I experienced the following error:

screen shot 2016-07-23 at 17 28 06

MTW used to have a function that broke down long URL requests to Google Translate into smaller requests. We should do something similar for Yandex too.

### PR DESCRIPTION
**Pull request by ankit-m**
I have limited the number of words per request to 500. The documentation does not show mention any limit. 

(closes #163)

### CODE REVIEW

**Comment by ankit-m** [comment]
@Ceilican for very long pages, it takes a huge amount of time to replace all the words. We need to make the `deepHTMLReplacement` function more efficient.

File: lib/scripts/services/yandexTranslate.js [hunk 1]
```diff
@@ -43,20 +47,68 @@ export class YandexTranslate {
...
+  toList(words) {
+    var wordList = [];
+    for (let word in words) {
+      wordList.push(word);
+    }
+    return wordList;
+  }
+
+  /**
+   * Breaks the words list into 128 words and returns
```
Comment (Ceilican) [inline lib/scripts/services/yandexTranslate.js]: 128 --> 500?

**Comment by Ceilican** [comment]
Thanks!

File: lib/scripts/services/yandexTranslate.js (hunk 1 above)
Comment (ankit-m) [inline lib/scripts/services/yandexTranslate.js]: I am sorry, I took this function from `googleTranslate` and forgot to edit that. Will correct it.
